# Generated by Django 5.1.1 on 2024-09-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_tasklist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
