# Generated by Django 5.1.1 on 2024-09-18 09:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_opt_remove_tasklist_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='opt',
            new_name='User',
        ),
    ]
