# Generated by Django 5.1.1 on 2024-09-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_rename_opt_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
    ]
