# Generated by Django 5.1.1 on 2024-09-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_registrationotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationOtp',
        ),
    ]
