# Generated by Django 5.1.1 on 2024-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_viewset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSerialize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
