# Generated by Django 5.1.1 on 2024-09-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_viewset', '0002_testserialize'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestSerialize',
            new_name='TestS',
        ),
    ]
