# Generated by Django 5.1.1 on 2024-09-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_viewset', '0003_rename_testserialize_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
