# Generated by Django 5.1.2 on 2024-10-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0008_album_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_1.track',),
        ),
    ]
