# Generated by Django 5.1.1 on 2024-10-03 06:45

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(max_length=50)),
                ('Contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_name', models.CharField(max_length=30)),
                ('Author_subject', models.CharField(max_length=50)),
                ('Author_code', models.IntegerField(unique=True)),
                ('Author_qualification', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Pincode', models.IntegerField()),
                ('Contact_no', models.IntegerField()),
                ('Member_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publisher_name', models.CharField(max_length=50)),
                ('Publisher_code', models.IntegerField(unique=True)),
                ('Publisher_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_code', models.IntegerField(unique=True)),
                ('Contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Library_name', models.CharField(max_length=50)),
                ('Library_address', models.CharField(max_length=50)),
                ('Contact_no', models.IntegerField()),
                ('Library_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Liberary.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Books_status', models.BooleanField(default=False)),
                ('Books_price', models.IntegerField()),
                ('Books_author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Liberary.author')),
                ('Books_library', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Liberary.library')),
                ('Books_publisher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Liberary.publisher')),
                ('Books_vendor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Liberary.vendor')),
            ],
        ),
    ]
