# Generated by Django 5.1.1 on 2024-09-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0002_post_image_like_image_comment_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeByUser',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
