# Generated by Django 5.1.1 on 2024-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0003_alter_userdata_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
