# Generated by Django 5.1.1 on 2024-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0003_delete_likebyuser_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_by', models.IntegerField()),
                ('request_to', models.IntegerField()),
                ('request_accepted', models.BooleanField(default=False)),
            ],
        ),
    ]
