# Generated by Django 5.1.1 on 2024-09-23 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0004_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_user',
            name='request_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_by', to='fbapp.user'),
        ),
        migrations.AlterField(
            model_name='request_user',
            name='request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_to', to='fbapp.user'),
        ),
    ]
