# Generated by Django 5.1.1 on 2024-09-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0005_delete_hotel_userdata_comment_userdata_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='post',
            field=models.FileField(upload_to='images'),
        ),
    ]
