# Generated by Django 5.1.1 on 2024-10-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgre_app', '0003_postgres_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgres_employee',
            name='age',
        ),
    ]
