# Generated by Django 5.1.1 on 2024-10-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgre_app', '0004_remove_postgres_employee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgres_employee',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
