# Generated by Django 5.1.1 on 2024-10-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgre_app', '0005_postgres_employee_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgres_data',
            name='age',
        ),
    ]
