# Generated by Django 5.1.1 on 2024-10-10 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postgre_app', '0007_postgres_data_age_alter_postgres_employee_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgres_employee',
            name='age',
        ),
    ]
