# Generated by Django 5.1.1 on 2024-10-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgre_app', '0008_remove_postgres_employee_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='newmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='postgres_employee',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
